app/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, jsonify
import re, os, base64
from PIL import Image
from datetime import datetime

from .utils import *
from . import lib_stores_db

from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash

all_routes = Blueprint("all_routes", __name__)

# display all stores
@all_routes.route("/stores/")
def display_all_stores():
    all_existing_stores = lib_stores_db.execute("SELECT * FROM stores ORDER BY RANDOM();")
    
    # convert each BLOB profile picture to a base64 string that can be used as src in an `img` tag
    for store in all_existing_stores:
        if store['profile_picture']:
            store['profile_picture'] = base64.b64encode(store['profile_picture']).decode('utf-8')
    
    return render_template("stores.html", all_existing_stores=all_existing_stores)


@all_routes.route("/stores/<store_name_id>/")
def dynamic_store(store_name_id):
    store_name, store_id = store_name_id.split("+")
    
    # check for IndexError or any other error in the split to show that there is no `id` and claim the the route is invalid
    try:
        store_full_information = lib_stores_db.execute("SELECT * FROM stores WHERE id = ?;", store_id)[0]
    except Exception:
        flash(message=str(("Invalid Store!", "Error: The requested store does not exists in LIB Stores!")), category="danger")
        return redirect(url_for("all_routes.display_all_stores"))
    
    # check if the name passed with the url is the same as the name in the database for the user with the `id`
    if len(store_full_information) <= 0 or store_full_information['name'] != store_name.replace("-", " "):
        flash(message=str(("Invalid Store!", "Error: The requested store does not exists in LIB Stores!")), category="danger")
        return redirect(url_for("all_routes.display_all_stores"))
    
    # convert the store's profile picture from BLOB to base64 string
    if store_full_information['profile_picture']:
        store_full_information['profile_picture'] = base64.b64encode(store_full_information['profile_picture']).decode('utf-8')
    
    store_products = lib_stores_db.execute("SELECT * FROM products WHERE store_id = ?", store_id)
        
    product_id_and_photos = {}
    
    for product_info in store_products:
        # format the price as USD ($29.93)
        product_info['price'] = usd(product_info['price'])
        
        product_id_and_photos[product_info['id']] = lib_stores_db.execute(
            """
                SELECT picture FROM product_pictures
                WHERE product_id = ?
            """,
            product_info['id']
        )
        
    """
        loop through the `store_products` and use the id to uniquely 
        identify elements in the `product_id_and_info` dictionary that would have
        a key that will be an id of a product and the value of the `product_id_and_info`
        is an array that was returned by the SQL query which would be a list
    """
    
    for product_info in store_products:
        for info_and_id in product_id_and_photos[product_info['id']]:
            # conver each picture BLOB that returned from the SQL query to a base 64 image
            info_and_id['picture'] = base64.b64encode(info_and_id['picture']).decode("utf-8")
    
    return render_template("stores.html", store_full_information=store_full_information, store_products=store_products, product_id_and_photos=product_id_and_photos)


@all_routes.route("/sign-up/", methods=['GET', 'POST'])
def sign_up():
    return render_template("signup.html", ACCOUNT_TYPES=ACCOUNT_TYPES)


@all_routes.route("/sign-up/store/", methods=['GET', 'POST'])
def sign_up_as_store():
    
    # clear the session so the user don't have passwords suggestions showing up from their saved passwords in their web browser
    session.clear()
    
    if request.method == "POST":
        form_data = request.form
        
        # get data from individual input fields
        store_name = form_data.get("store_name")
        email = form_data.get("email")
        password = form_data.get("password")
        confirm_password = form_data.get("confirm_password")
        contact_number = form_data.get("contact_number")
        mobile_money_number = form_data.get("mobile_money_number")
        head_branch_location = form_data.get("head_branch_location")
        branches_location = form_data.get("branches_location")
        product_categories = form_data.get("product_categories")
        about_store = form_data.get("about_store")
        profile_picture = request.files.get("profile_picture_input")
        
        # validate store's sign up information
        
        # store name too short
        if store_name and len(store_name.strip()) < 2:
            return refill_input_fields(sign_up_type="store", store_name_error="Store Name must be atleast 2 character long")
        
        # store name too long
        elif store_name and len(store_name.strip()) > 150:
            return refill_input_fields(sign_up_type="store", store_name_error="Store Name must be atmost 150 character long")
        
        # ensure store name does not have special characters
        elif store_name and find_punctuation_in_str(store_name.strip()):
            return refill_input_fields(sign_up_type="store", store_name_error="Store Name must not contain any special character")
        
        # email not valid
        elif email and re.match(email_regex, email) is None:
            return refill_input_fields(sign_up_type="store", email_error="Invalid email address!")
        
        # check if the email already exists
        elif len(lib_stores_db.execute("SELECT email FROM stores WHERE email = ?", email)) > 0:
                return refill_input_fields(sign_up_type="store", email_error="Email address already exists!")

        # contact number not valid
        elif not validate_contact_number(contact_number):            
            return refill_input_fields(sign_up_type="store", contact_number_error="Invalid contact number! e.g. 0775326934 or +231555943559 or 0888061282")
        
        # check if the contact_number already exists
        elif len(lib_stores_db.execute("SELECT contact_number FROM stores WHERE contact_number = ?", clean_phone_number(contact_number))) > 0:
            return refill_input_fields(sign_up_type="store", contact_number_error="This contact number already exists!")
        
        # mobile money number not valid
        elif not validate_mobile_money_number(mobile_money_number):
            return refill_input_fields(sign_up_type="store", mobile_money_number_error="Invalid mobile money number! e.g. 0888061282 or +231555943559")
        
        # check if the mobile_money_number does not already exists
        elif len(lib_stores_db.execute("SELECT mobile_money_number FROM stores WHERE mobile_money_number = ?", clean_phone_number(mobile_money_number))) > 0:
            return refill_input_fields(sign_up_type="store", mobile_money_number_error="This mobile money number address already exists!")
        
        # ensure password len(password) >= 12 and lower upper punc and digit in password
        elif not validate_password(password):
            return refill_input_fields(sign_up_type="store", password_error="Password must be atleast 8 characters long and must have atleast one special symbol, uppercase, lowercase and number")

        # ensure the confirmation password is the same as the first password
        elif confirm_password != password:
            return refill_input_fields(sign_up_type="store", confirm_password_error="Passwords don't match!")
        
        # ensure the user actually gave a head branch
        elif head_branch_location is None or len(head_branch_location) < 2:
            return refill_input_fields(sign_up_type="store", head_branch_location_error="Please provide a descriptive Head Branch location!")
        
        # validate profile picture
        elif profile_picture and profile_picture.filename and len(profile_picture.filename) < 5:
            return refill_input_fields(sign_up_type="store", file_upload_error="Profile Picture / Logo is required!")

        elif not isinstance(profile_picture, FileStorage) or profile_picture is None or profile_picture.filename is None:
            return refill_input_fields(sign_up_type="store", file_upload_error="Please provide a valid image!")

        contact_number = validate_contact_number(contact_number)
        mobile_money_number = validate_contact_number(mobile_money_number)

        picture_data = None

        if profile_picture:
            # save the file to a temporary location to open it and read its information, then store in the database as BLOB
            filename = secure_filename(profile_picture.filename)
            filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            
            # save the image to the temporary upload folder
            profile_picture.save(filepath)

            # final image validation to check the dimensions and format of the uploaded file
            if validate_image(filepath) == False:
                return refill_input_fields(sign_up_type="store", file_upload_error="Please provide a valid image!")

            # compress the image so it can be stored in the browser session
            compressed_image = Image.open(filepath)
            compressed_image.save(filepath, quality=10)
            
            with open(filepath, 'rb') as uploaded_picture:
                picture_data = uploaded_picture.read()
             
        # update product_categories and branches_location per the changes in teh validation function
        branches_location = branches_location and validate_product_categories_and_branches_location(branches_location)[0] or None

app/templates/admin.html
{% extends "layout.html" %}

{% block title %}Admin{% endblock title %} 

{% block main %}

<h2>
    Admin Page
</h2>

<!-- Button to trigger file download -->
<a href="{{ db_path }}" download="DB.db">
    <button class="btn btn-primary" onclick="window.location.href='/';">
        Download Database File
	</button>
</a>

{% endblock main %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit&family=Stylish&display=swap" rel="stylesheet">

    <link rel="icon" href="{{ url_for('static', filename="imgs/site_logo.png" )}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homepage.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stores.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/general.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signup.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">

    <style>
        {% block additional_style %}{% endblock additional_style %}
    </style>

    <title>{% block title %}{% endblock title %} | LIB Stores</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-light" id="navbar">
        <a class="navbar-brand" href="{{ url_for("index") }}">
            <img src="{{ url_for("static", filename="imgs/site_logo.png") }}" alt="Logo" id="site_logo">
		</a>

        <button class="navbar-toggler" id="navbar_toggle_btn" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if session['current_user_info'] %}
            
                <ul class="mr-auto navbar-nav" id="store_product_latest_ul">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('all_routes.display_all_stores') }}">Stores</a>
                    </li>
                    {% if session['current_user_info']['account_type'] == "store" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('all_routes.add_product') }}">Add Product</a>
                        </li>
                    {% endif %}
                </ul>
                    
				<form  class="my-2 form-inline my-lg-0" id="search_form">
                    <input class="form-control" type="search" placeholder="Type to Search" id="search_input" aria-label="Search" name="full_search">
                    <button class="btn btn-outline-success" id="search_btn" type="submit">Search</button>
                </form>

                <ul class="mr-auto navbar-nav" id="profile_and_logout_ul">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('all_routes.logout') }}">Log Out</a>
                    </li>
                    <li class="nav-item" id="profile_picture_li">
                        <a class="nav-link" href="{{ url_for('index') }}">
                            {% if session['current_user_info']['account_type'] == "customer" or not session['profile_picture'] %}
                                <img src="{{ url_for("static", filename='imgs/shopping_bag.jpeg') }}" alt="Profile Picture" id="profile_picture">
                            {% else %}
                                <img src="data:image/png;base64,{{ session['profile_picture'] }}" alt="Profile Picture" id="profile_picture">
                            {% endif %}
                        </a>
                    </li>
                </ul>

            {% else %}

                <ul class="mr-auto navbar-nav" id="store_product_latest_ul">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('all_routes.display_all_stores') }}">Stores</a>
                    </li>
                </ul>

                <form class="my-2 form-inline my-lg-0" id="search_form">
                    <input class="form-control" type="search" placeholder="Type to Search" id="search_input" aria-label="Search" name="full_search">
                    <button class="btn btn-outline-success" id="search_btn" type="submit">Search</button>
                </form>

                <ul class="mr-auto navbar-nav" id="signup_login_ul">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('all_routes.sign_up') }}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('all_routes.login') }}">Login</a>
                    </li>
                </ul>
            
            {% endif %}
        </div>
    </nav>
	
	<!-- add margin top to the search results div so it won't cover the input field on mobile phone -->
    {% if session['current_user_info'] %}
        {% if session['current_user_info']['account_type'] == "store" %}
            <button onclick="increaseSearchResultsDivMarginTop()" id="increaseSearchResultsDivTopMarginBtn" class="none"></button>
        {% endif %}
    {% endif %}

	<div id="search_results_div"></div>
    
    {% if get_flashed_messages() %}
        {% set flashed_messaged = get_flashed_messages(with_categories=True) %}

        <button type="button" id="display_flashed_messages_modal_btn" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">See Modal</button>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog alert-{{ flashed_messaged[0][0] }}" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{{ flashed_messaged[0][1][0] }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <p>
                                {{ flashed_messaged[0][1][1] }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

    <main>
        {% block main %}

        {% endblock main %}
    </main>

    <footer></footer>
    
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <script src="{{ url_for('static', filename='js/app.js')}}"></script>
</body>
</html>

app/templates/signup.html
{% extends "layout.html" %}

{% block title %}Sign Up{% endblock title %}

{% block main %}

    {% if as_store or as_customer %}
	<div id="signup_form_side_by_side_wrapper" class="d-flex justify-content-between">
		<div id="signup_type_div" class="text-center flex-column d-flex align-items-center justify-content-center">
			<h1>Sign Up</h1>
			{% if as_store %}
				<img class="mt-3" src="{{ url_for("static", filename='imgs/store_icon.png') }}" alt="Store Icon">
			{% else %}
				<img class="mt-3" src="{{ url_for("static", filename='imgs/customer_icon.png') }}" alt="Customer Icon">
			{% endif %}
		</div>

		<div id="signup_info_div">
			{% if as_store %}
				<form method="POST" action="{{ url_for('all_routes.sign_up_as_store') }}" id="signup_form" enctype="multipart/form-data">
					<div class="form-group">
						<label for="store_name_input">Store Name</label>
						<input type="text" name="store_name" required autofocus class="form-control" id="store_name_input" placeholder="Enter Store Name" required {% if store_name %}value="{{ store_name }}"{% endif %}>

						{% if store_name_error %}
							<div class="invalid_feedback">
								{{ store_name_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for"contact_number_input">Contact Number</label>
						<input type="tel" name="contact_number" required class="form-control" id="contact_number_input" aria-describedby="contact_number_help" placeholder="Contact Number" required {% if contact_number %}value="{{ contact_number }}"{% endif %}>
						<small id="contact_number_help" class="form-text text-muted">This number will be available to customers to contact your store!</small>

						{% if contact_number_error %}
							<div class="invalid_feedback">
								{{ contact_number_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for"mobile_money_number_input">Lonestar Mobile Number</label>
						<input type="tel" required name="mobile_money_number" class="form-control" id="mobile_money_number_input" placeholder="Mobile Money Number" required {% if mobile_money_number %}value="{{ mobile_money_number }}"{% endif %}>
						<small id="about_store_help" class="form-text text-muted">This number will be used to purchase items!</small>

						{% if mobile_money_number_error %}
							<div class="invalid_feedback">
								{{ mobile_money_number_error }}
							</div>
						{% endif %}
					</div>
					
					<div class="form-group">
						<label for="head_branch_location_input">Head Branch Location</label>
						<input name="head_branch_location" class="form-control" required id="head_branch_location_input" aria-describedby="head_branch_location_help" placeholder="Enter Head Branch Location" required {% if head_branch_location %} value="{{ head_branch_location }}"{% endif %}>
						<!--add a pop up to tell the delimeter-->
						<small id="head_branch_location_help" class="form-text text-muted">Enter your Head / Main Branch Location.</small>

						{% if head_branch_location_error %}
							<div class="invalid_feedback">
								{{ head_branch_location_error }}
							</div>
						{% endif %}
					</div>
					
					<div class="form-group">
						<label for="email_input">Email address</label>
						<input type="email" name="email" class="form-control" id="email_input" aria-describedby="email_help" placeholder="Enter email address" required {% if email %}value="{{ email }}"{% endif %}>
						<small id="email_help" class="form-text text-muted">We'll never share your email with anyone else. It will be used to notify your store on situations.</small>

						{% if email_error %}
							<div class="invalid_feedback">
								{{ email_error }}
							</div>
						{% endif %}
					</div>
					
					<div class="form-group">
						<label for"password_input">Password</label>
						<input type="password" name="password" required class="form-control password_input" id="password_input" placeholder="Password" required {% if password %}value="{{ password }}"{% endif %}>

						{% if password_error %}
							<div class="invalid_feedback">
								{{ password_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for"confirm_password_input">Confirm Password</label>
						<input type="password" name="confirm_password" required class="form-control password_input" id="confirm_password_input" placeholder="Confirm Password" required {% if confirm_password %}value="{{ confirm_password }}"{% endif %}>

						{% if confirm_password_error %}
						<div class="invalid_feedback">
							{{ confirm_password_error }}
						</div>
						{% endif %}

						<input type="checkbox" id="show_passwords">
						<label for="show_passwords" class="show_passwords_label">Show Passwords</label>
					</div>
					
					<!--<div class="form-group"> -->
					<!--    <label for="product_categories_textarea">Categories of Product</label> -->
					<!--    <textarea name="product_categories" class="form-control" id="product_categories_textarea" aria-describedby="product_categories_help" placeholder="Enter Products Type" required>{% if product_categories %}{{ product_categories }}{% endif %}</textarea> -->
					<!--    <!-1-add a pop up to tell the delimeter -->
					<!--    <small id="product_categories_help" class="form-text text-muted">Enter the Categories of Products you sell seperated by a ',' (comma) avoid `and` use `&amp;` instead.<br>Example: Construction Material, Home Appliances, Office Supplies, Stationary</small> -->

					<!--    {% if product_categories_error %} -->
					<!--        <div class="invalid_feedback"> -->
					<!--            {{ product_categories_error }} -->
					<!--        </div> -->
					<!--    {% endif %} -->
					<!--</div> -->

					<!--<div class="form-group"> -->
					<!--    <label for="branches_location_textarea">Branches Location</label> -->
					<!--    <textarea name="branches_location" class="form-control" id="branches_location_textarea" aria-describedby="branches_location_help" placeholder="Enter Branches Location" required>{% if branches_location %}{{ branches_location }}{% endif %}</textarea> -->
					<!--    1-add a pop up to tell the delimeter -->
					<!--    <small id="branches_location_help" class="form-text text-muted">Enter each Branch Location seperated by a ',' (comma) avoid `and` use `&amp;` instead.<br>Example: Randall &amp; Benson Street, Red Light, Duala, Waterside, ELWA Junction</small> -->

					<!--    {% if branches_location_error %} -->
					<!--        <div class="invalid_feedback"> -->
					<!--            {{ branches_location_error }} -->
					<!--        </div> -->
					<!--    {% endif %} -->
					<!--</div> -->

					<div class="form-group">
						<label>Upload Profile / Logo</label>

						<div id="profile_picture_preview_div"></div>

						<div class="custom-file">
							<input type="file" class="custom-file-input" name="profile_picture_input" id="customFile">
							<label class="custom-file-label" for="customFile">Select Picture</label>
						</div>

						{% if file_upload_error %}
							<div class="invalid_feedback">
								{{ file_upload_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for"about_store_textarea">About Store</label>
						<textarea id="about_store_textarea" class="form-control" name="about_store" placeholder="More Information About Store" aria-describedby="about_store_help">{% if about_store %}{{ about_store }}{% endif %}</textarea>
						<small id="about_store_help" class="form-text text-muted">Optional: Provide Information about your store that may not have been requested!</small>
					</div>
					
					<button style="margin-bottom: 100px" type="submit">Sign Up</button>
				</form>
			{% else %}
				<form action="{{ url_for("all_routes.sign_up_as_customer") }}" method="POST" id="signup_form">
					<div class="form-group">
						<label for="full_name_input">Full Name</label>
						<input type="text" name="full_name" autofocus class="form-control" id="full_name_input" placeholder="Enter Full Name" required {% if full_name %}value="{{ full_name }}"{% endif %}>

						{% if full_name_error %}
							<div class="invalid_feedback">
								{{ full_name_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="email_input">Email address</label>
						<input type="email" name="email" class="form-control" id="email_input" placeholder="Enter Email Address" required {% if email %}value="{{ email }}"{% endif %}>

						{% if email_error %}
							<div class="invalid_feedback">
								{{ email_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="mobile_money_number_input">Mobile Money Number</label>
						<input type="tel" name="mobile_money_number" class="form-control" id="mobile_money_number_input" placeholder="Enter Mobile Money Number" required {% if mobile_money_number %}value="{{ mobile_money_number }}"{% endif %}>
						<small id="about_store_help" class="form-text text-muted">This number is what will be used to purchase items!</small>

						{% if mobile_money_number_error %}
							<div class="invalid_feedback">
								{{ mobile_money_number_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="password_input">Password</label>
						<input type="password" name="password" class="form-control password_input" id="password_input" placeholder="Enter Password" required {% if password %}value="{{ password }}"{% endif %}>

						{% if password_error %}
							<div class="invalid_feedback">
								{{ password_error }}
							</div>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="confirm_password_input">Confirm Password</label>
						<input type="password" name="confirm_password" class="form-control password_input" id="confirm_password_input" placeholder="Confirm Password" required {% if confirm_password %}value="{{ confirm_password }}"{% endif %}>

						{% if confirm_password_error %}
							<div class="invalid_feedback">
								{{ confirm_password_error }}
							</div>
						{% endif %}

						<input type="checkbox" id="show_passwords">
						<label for="show_passwords" class="show_passwords_label">Show Passwords</label>
					</div>

					<button style="margin-bottom: 100px" type="submit">Sign Up</button>
				</form>
			{% endif %}
		</div>
	</div>
    
    {% else %}
        <div id="account_type_div">
            {% for account_type in ACCOUNT_TYPES %}
                <a href="/sign-up/{{ account_type.type | lower }}">
                    <div>
                        <div class="account_type_img_div">
                            <img src="{{ account_type.path }}" alt="{{ account_type.type | title }}">
                        </div>

                        <div class="account_type_title_div">
                            <h2>{{ account_type.type | title }}</h2>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% endif %}

    

{% endblock main %}